### ISSUE TITLE
xmatch warning with DR2 epoch2015.5

### ISSUE THREAD

**Issue by henrysky** [jobovy/gaia_tools#11]
The warning appeared for Gaia DR2 catalog about being epoch 2015.5 but not epoch 2015

And was wondering maybe if `ref_epoch` is a field that is presented in `cat1` or `cat2`, then `ref_epoch` should be used in case `ref_epoch` is different for each star in future gaia release??

example code:
```
# where `xmatched_allcolumns` is Gaia DR2 catalog
idx_1, idx_2, sep = gaia_tools.xmatch.xmatch(apogeedr14, xmatched_allcolumns, 
colRA1='ra',colDec1='dec',  colRA2='ra',colDec2='dec', colpmRA2='pmra',colpmDec2='pmdec', 
epoch2=2015.5)
```
will lead to a warning
```
/home/henrysky/gaia_tools/gaia_tools/xmatch/__init__.py:51: 
UserWarning: You appear to be using a Gaia catalog, but are not setting the epoch to 2015., which may lead to incorrect matches 
warnings.warn("You appear to be using a Gaia catalog, but are not setting the epoch to 2015., which may lead to incorrect matches")
```

**Comment by jobovy** [comment]
Checked in a fix in 91152ac, please check (I think it does everything you want).
