### ISSUE TITLE
Cross-matching APOGEE with Gaia DR2 in Vizier

### ISSUE THREAD

**Issue by jmackereth** [jobovy/gaia_tools#12]
A student working at LJMU (Andrew Mason) noted that there seems to be an issue when trying to get the complete Gaia-DR2 table crossmatched to the APOGEE data. Loading the APOGEE data:
```python
apogee_cat= gload.apogee(use_astroNN=True) 
```
then attempting the x-match using CDS:
```python
gaia2_matches, matches_indx= xmatch.cds(apogee_cat,colRA='RA',colDec='DEC',xcat='vizier:I/345/gaia2', gaia_all_columns=True)
```
returns this error message:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-1ed8a33ff93d> in <module>
----> 1 gaia2_matches, matches_indx= xmatch.cds(apogee_cat,colRA='RA',colDec='DEC',xcat='vizier:I/345/gaia2', gaia_all_columns=True)

/anaconda3/lib/python3.7/site-packages/gaia_tools-0.2-py3.7.egg/gaia_tools/xmatch/__init__.py in cds(cat, xcat, maxdist, colRA, colDec, selection, epoch, colpmRA, colpmDec, savefilename, gaia_all_columns)
    162     result.close()
    163     # Directly match on input RA
--> 164     ma= cds_load(resultfilename)
    165     if gaia_all_columns:
    166         from astroquery.gaia import Gaia

/anaconda3/lib/python3.7/site-packages/gaia_tools-0.2-py3.7.egg/gaia_tools/xmatch/__init__.py in cds_load(filename)
    216         return numpy.genfromtxt(filename, delimiter=',', skip_header=0,
    217                                 filling_values=-9999.99, names=True,
--> 218                                 dtype='float128')
    219 
    220 def cds_matchback(cat,xcat,colRA='RA',colDec='DEC',selection='best',

/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows, encoding)
   2196                         dtype = np.dtype(ttype)
   2197             #
-> 2198             output = np.array(data, dtype)
   2199             if usemask:
   2200                 if dtype.names:

ValueError: invalid literal for long double: <head><title>504 Gateway Time-out</title></head>
```

This seems to be an issue with a time-out on the Vizier side. I imagine the fix will be relatively simple (I may come up with a fix for this soon!), but I just wanted to raise it as an issue now to make it known!

**Comment by jobovy** [comment]
Does this happen every time you run this (including other times/days)? This indeed seems to be an issue with Vizier timing out during the original cross-match, which we could catch, but there's not much to do about it if it's just that the service is for some reason unavailable. Of course, if this consistently happens, then perhaps there's an issue with the code.

Note that you should also be able to just do
```
apogee_cat= gload.apogee(use_astroNN=True,xmatch='gaiadr2',gaia_all_columns=True)
```
instead of the two-step approach (but internally it does the same thing). This has the advantage that it caches the match, so the next time you run it it doesn't call CDS again.

**Comment by jmackereth** [comment]
Thanks for this, Jo!

Yes, this does seem to happen every time, and does not happen when cross matching, for example, GALAH. The single-step approach also encounters the same error. Therefore, I assume this is something in the code regarding the apogee catalogue...

Going to fork the repo and see if I can fix this.

**Comment by jobovy** [comment]
Have you made any progress on this? I've just run into this problem myself...

**Comment by jobovy** [comment]
I think I have tracked this down to the time-out happening whenever the xMatch takes longer than 1 minute, which seems to happen around ~350,000 stars. Not sure whether that is consistent with the GALAH behavior, but I've emailed the xMatch service to ask about this....

**Comment by jobovy** [comment]
I pushed a possible fix, by recursively splitting the data set until it's small enough to be processed by CDS. Please test!

**Comment by DHortaD** [comment]
Hello, 

I am having a separate problem. I run the code as above and it seems to complete. However the output is a file with just the RA and DEC columns. I have included the "gaia_all_columns=True" kwarg, but it seems to have no effect. I attach my code below:

#crossmatch the datasets
gaia2_matches, matches_indx= xmatch.cds(data,colRA='RA',colDec='DEC',xcat='vizier:I/345/gaia2', gaia_all_columns=True)

#find the matches
data = data[matches_indx]

#save it
with open(save_path+'dr16_full.dat', 'wb') as f:
    pickle.dump(apogee_cat, f) 

The file I am trying to cross-match is quite large, could this be the problem?

Thanks
Danny

**Comment by jobovy** [comment]
I'm confused about this issue: is the `data` array the one you are trying to save and that is simply RA and Dec? The matched info should be in ``gaia2_matches``. The code will produce an intermediate file that just has RA and Dec for all sources (that's what's uploaded to CDS to do the match), maybe that is what you are referring to?

**Comment by DHortaD** [comment]
Ok I think that was exactly the problem. I was reading in the RA and DEC table instead of the xmatched table... Apologies for this.
