### ISSUE TITLE
No module found: astropy.extern.six

### ISSUE THREAD

**Issue by dkashyap1993** [jobovy/gaia_tools#24]
I am trying to import query from gaia_tools i.e. :
**from gaia_tools import query**
However, I have been getting the error that the module six could not be found in astropy. I tried importing six on its own: 
**import six
from gaia_tools import query**
But I am still getting the same error. Any suggestions on how to fix this?

**Comment by jobovy** [comment]
Could you send the full error message? I don't think we explicitly use ``astropy.extern.six`` in ``gaia_tools``, so I think this is most likely an issue with another of the dependencies (probably ``astroquery``, you could try updating that).

**Comment by dkashyap1993** [comment]
This is the error I got for the following lines:
**import numpy
import pandas
from astropy import units
from galpy.util import bovy_coords, bovy_plot
import six
from gaia_tools import query
#from astroquery.gaia import Gaia
import matplotlib.colors as mcolors
from misc import bootstrap
%pylab inline**
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-17fc183ba5e9> in <module>
      4 from galpy.util import bovy_coords, bovy_plot
      5 import six
----> 6 from gaia_tools import query
      7 #from astroquery.gaia import Gaia
      8 import matplotlib.colors as mcolors

~/anaconda3/lib/python3.6/site-packages/gaia_tools-0.2-py3.6.egg/gaia_tools/query/__init__.py in <module>
      3 from . import cache as query_cache
      4 
----> 5 from ._query import query
      6 from .make_gaia_query import make_query, make_simple_query
      7 

~/anaconda3/lib/python3.6/site-packages/gaia_tools-0.2-py3.6.egg/gaia_tools/query/_query.py in <module>
      4 import numpy
      5 from astropy.table import Table
----> 6 from astroquery.gaia import Gaia
      7 
      8 from . import cache as query_cache

~/anaconda3/lib/python3.6/site-packages/astroquery/gaia/__init__.py in <module>
     16 """
     17 
---> 18 from astroquery.utils.tap.core import TapPlus
     19 from astropy import config as _config
     20 

~/anaconda3/lib/python3.6/site-packages/astroquery/utils/__init__.py in <module>
      6 import warnings
      7 
----> 8 from .progressbar import *
      9 from .download_file_list import *
     10 from .class_or_instance import *

~/anaconda3/lib/python3.6/site-packages/astroquery/utils/progressbar.py in <module>
      2 import gzip
      3 import sys
----> 4 from astropy.extern.six import StringIO
      5 from astropy.extern.six.moves import urllib
      6 from astropy.io import fits

ModuleNotFoundError: No module named 'astropy.extern.six'

**Comment by jobovy** [comment]
Yes, so this is an issue in ``astroquery``. If upgrading ``astroquery`` doesn't resolve your issue, I would recommend raising the issue at [astroquery](https://github.com/astropy/astroquery/issues) (you can refer to this one as ``jobovy/gaia_tools#24``)
