### ISSUE TITLE
problem reading APOGEE DR13 file?

### ISSUE THREAD

**Issue by andresmeza** [jobovy/gaia_tools#4]
I'm trying to cross match the APOGEE DR13 file (allStar-l30e.2.fits) with GAIA TGAS but when I read this file I got only 155,632 stars instead of 164,562. Maybe I'm doing something wrong but I changed the file for the DR14 pre-release and I got again only 155,632 stars. I'm using python 3.5 (anaconda). What's going on?

![apogee-tgas](https://cloud.githubusercontent.com/assets/11726283/23375049/a0f95e26-fd05-11e6-9ee5-0edc88496df8.png)

**Comment by jobovy** [comment]
You probably have the [jobovy/apogee](https://github.com/jobovy/apogee) module installed, in which case ``gload.apogee`` uses the [``apogee.tools.read.allStar``](https://github.com/jobovy/apogee/blob/master/apogee/tools/read.py#L92) function to read the data. By default this function makes some cuts to the catalog. If you use
```
apogee_cat= gload.apogee(raw=True)
```
you will get the entire file.

**Comment by jobovy** [comment]
PS: this also means that the code looks for the file in the data directory for the ``apogee`` module, not that for the ``gaia_tools`` module, which is probably why changing the file to the DR14 version did nothing.

**Comment by andresmeza** [comment]
Yes, I do have the apogee module installed. It works fine now. Thank you.
