### ISSUE TITLE
[OS Error] Downloading the catalog

### ISSUE THREAD

**Issue by jtbuch** [jobovy/gaia_tools#6]
Hi Jo,

I downloaded and set up `gaia_tools` as described in the installation file: including the dependencies and setting the environment variable GAIA_TOOLS_DATA to a local directory where I want my data to be downloaded. However, when I run the example code to load the TGAS data I get the following error:
<img width="1141" alt="img_1" src="https://user-images.githubusercontent.com/29380821/32517707-37c21b5e-c3d5-11e7-81bd-5eac028fd711.png"> 

<img width="1110" alt="img_2" src="https://user-images.githubusercontent.com/29380821/32517708-37ce1332-c3d5-11e7-8cb9-ab4db3f9ebd9.png">

I wonder if this is some basic error on my side in setting things up, or something else.

Any help will be appreciated!

**Comment by jobovy** [comment]
Hi Jatan,

Do you have ``wget`` installed? That is often the thing that is missing when you get a cryptic error message like this. ``wget`` is a standard unix utility to download files, but you might have to install it yourself.

**Comment by jtbuch** [comment]
That was spot-on!

Thanks for the prompt response, Jo.

Cheers,
Jatan
