### ISSUE TITLE
Matching stars with RAVE

### ISSUE THREAD

**Issue by jtbuch** [jobovy/gaia_tools#7]
Hi Jo,

I tried to obtain the stars common to RAVE and TGAS using: 
1. `gaia_tools.xmatch.xmatch()`, and 
2. Considering the non-nan, unique stars directly from the TGAS data included in the RAVE catalog. The code I used was:

`temp_indx= np.where(np.isnan(rave_cat['parallax_TGAS'])==False)[0] \
_, tgas_indx= np.unique(rave_cat['parallax_TGAS'][temp_indx], return_index=True)`

where `len(temp_indx)= 249,603` and matches the value that RAVE claims here: https://www.rave-survey.org/project/   and `len(tgas_indx)=210,368` is the number of unique stars that should roughly match the value I obtain from 1.

However, there's only 118329 stars in common after using `gaia_tools.xmatch.xmatch()` .

I went through your source code and it had no obvious bugs. Any idea why there would be such a discrepancy?

Best,
Jatan

**Comment by jobovy** [comment]
Did you use the method [here](https://github.com/jobovy/gaia_tools#match-rave-to-tgas-taking-into-account-the-epoch-difference)? That gives me 216,201 stars, not 118,329.

**Comment by jtbuch** [comment]
This checks out.

It seems that the discrepancy was due to matching with RAVE after putting the selection function cuts on tgas. 

Thanks, 
Jatan

**Comment by jobovy** [comment]
That makes sense, that would remove about 50% of the match, because the selection function only covers about 50% of the sky.
