### ISSUE TITLE
Files are moved on http://cdn.gea.esac.esa.int server

### ISSUE THREAD

**Issue by henrysky** [jobovy/gaia_tools#8]
Files are moved on server.

For example, tgas dr1 fits files are moved from http://cdn.gea.esac.esa.int/Gaia/tgas_source/fits/ to http://cdn.gea.esac.esa.int/Gaia/gdr1/tgas_source/fits/. So gaia_tools can no longer download the files.

**Comment by henrysky** [comment]
I am so sorry I did not check that I did not used the latest commit :(

**Comment by jobovy** [comment]
Not a problem, I also only just saw this last weekend.
