### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jacobhhamer** [jobovy/gaia_tools#9]
Hi Jo,

After cloning the repository and following the install instructions (`sudo python setup.py install`), I get the following error: 

`Processing dependencies for gaia-tools==0.2`
`Searching for astropy`
`Reading https://pypi.python.org/simple/astropy/`
`Best match: astropy 3.0.4`
`Downloading https://files.pythonhosted.org/packages/4b/bf/9fba1226f7acfa63bc2d86e79173c72d46f3175687bf74856281c6f5db42/astropy-3.0.4.tar.gz#sha256=f5d37d20632ba74bd0b12a85179c12f64a9ea037ffc916d8a2de3be4f4656c76`
`Processing astropy-3.0.4.tar.gz`
`Writing /tmp/easy_install-hNpkhs/astropy-3.0.4/setup.cfg`
`Running astropy-3.0.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hNpkhs/astropy-3.0.4/egg-dist-tmp-AMBnCq`
`ERROR: Astropy requires Python 3.5 or later`
`error: Setup script exited with 1`

My python version is:
`$ python --version`
`Python 3.6.6 :: Anaconda custom (64-bit)`
 
I also confirmed that the python I'm running is in the anaconda install:
`$ which conda`
`/home/jacobhhamer/anaconda3/bin/conda`
`$ which python`
`/home/jacobhhamer/anaconda3/bin/python`

This persisted after doing a `conda update --all`.

Best,
Jacob

**Comment by jobovy** [comment]
This probably means that the python you think you are using is not the actual python used (sudo will use the root user's python, not yours). Maybe try:
```
sudo /home/jacobhhamer/anaconda3/bin/python setup.py install
```

**Comment by jobovy** [comment]
@jacobhhamer, did this resolve the issue? If so, please close the issue.
